name:    scientific-example
version: 0.1.0.0
github:  "joelelmercarlson/scientific-example"
license: GPL
extra-source-files: []

executables:
  scientific-example:
    main: Main.hs
    source-dirs: src
    dependencies:
     - base
     - aeson
     - bytestring
     - containers
     - unordered-containers
     - scientific
     - text
